<!DOCTYPE html>
<html lang="en">

<head>
    <title>Online Book Store</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet"
        type="text/css" />
    <link rel="stylesheet" href="../css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500&family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
        rel="stylesheet">

</head>

<body>

    <!--------------- Header -------------------->

    <?php include('header.php'); ?>

    <!------------- terms & conditions ----------->
    <div class="container-fluid">
        <div class="row terms">
            <div class="heading">
                <h1>Terms of service</h1>
            </div>
            <h1 class="head1">terms and condition</h1>
            <ul class="a me-auto">
                <li>Subject to the Terms and Conditions of Use set out on this page, BookStation Private Limited
                    (hereinafter referred to as BookStation) and/or its affiliates provides you access to the website.
                    (hereinafter referred to as the “website”).</li>
                <li>Prior to the use of the said website, carefully read the set Terms and Conditions of Use which are
                    applicable to you for and during the use of the said website. By using this website, you are deemed
                    to have read the Terms and Conditions of Use and agree to be legally bound by the said Terms and
                    Conditions of Use.</li>
                <li>Further, any current or future use of the website or its services, subjects you to the terms and
                    conditions, and the applicable guidelines enforceable by law (hereinafter referred to as “Terms”),
                    to which BookStation and its services are subjected to, or, to the said Terms that are applicable on
                    BookStation and its services. If the Terms and Conditions of Use set herein are inconsistent with
                    such Terms, then the said Terms will hold.</li>
                <li>These "Terms and Conditions of Use" have been published in accordance with the Rule 3(1) of
                    Information Technology (Intermediary Guidelines) Rules, 2011. Further, this set of Terms and
                    Conditions of Use constitute an electronic record within the meaning of the applicable law. This
                    electronic record is generated by a computer system and does not require any physical or digital
                    signatures.</li>
            </ul>

            <h1 class="head1">TERMS RELATING TO YOUR USE OF BOOKSTATION</h1>


            <li>Your use of this website is at your own peril. You are responsible for maintaining the secrecy and the
                confidentiality of your account and password and for restricting access to your computer to prevent any
                unauthorised access to your account on this website.</li>
            <li>You agree to undertake all the responsibility for any and all activities that occur under your account
                or password. You must take all the appropriate imperative measures to maintain the confidentiality and
                security of your password. In case of a breach of such a confidentiality or if you have any reason to
                believe that your password has become known to someone else and/or is being used in any unauthorised
                manner, you must inform us of the said circumstances without any delay and must change the password, if
                so required.</li>
            <li>You are required to provide us with correct and complete details while registering and thereafter,
                ensure to update any change in the details that you provided at the time of registering without any
                unreasonable delay. You can access and update much of the information you provided us with in your
                account area of the website.</li>
            <li>You agree and acknowledge that you will use your registered account on the website to purchase products
                only for your personal use and not for business purposes.</li>
            <li>BookStation reserves the right to refuse access to the website, terminate accounts, remove or edit
                content at any time without notice to you.</li>
            </ul>

            <h1 class="user">PRIVACY</h1>
            <ul class="user1">
                <li>You signify and acknowledge that you have read our Privacy Policy, which by default governs your
                    visit, usage and access to this website.</li>
                <li>During the course of your visit, usage and access to this website, all the personal information
                    supplied to us by you will be treated as strictly confidential and in conformation with the Privacy
                    Policy and applicable laws and regulations.</li>
                <li>You must refrain from visiting, using and accessing this website, if you object to the said Privacy
                    Policy and the terms therein.</li>

            </ul>
            <h1 class="user">E-COMMERCE PLATFORM</h1>
            <ul class="user1">
                <li>You agree, understand and acknowledge that this website is an online platform that merely warrants
                    you to purchase products listed on the website at the price indicated therein at any time from any
                    location.</li>
                <li>You further agree, understand and acknowledge that BookStation is only a facilitator and is not and
                    cannot be a party to or control in any manner any transactions on the website.</li>
                <li>Suitably, the contract of sale of products on the website shall be a strictly bipartite contract
                    between you and the sellers on BookStation.</li>

            </ul>
            <h1 class="user"> ACCESS TO THE WEBSITE</h1>
            <ul class="user1">
                <li>We will take all reasonable measured to ensure the availability of an uninterrupted access to the
                    website and error-free transmissions. However, such access and/or transmissions may be interrupted
                    due to faulty internet. Additionally, the usage and access to this website may occasionally be
                    suspended or restricted, due to reasons pertaining to maintenance or induction of new facilities or
                    services at any time without prior notice.</li>
            </ul>

            <h1 class="user"> WEBSITE ACCESS</h1>
            <ul class="user1">
                <li>Subject to your compliance with these Conditions of Use and payment of applicable fees, if any,
                    BookStation grants you a limited licence to visit, use and access this website, for personal use
                    only, but not to download (other than page caching) or modify it, or any portion of it, except with
                    express written consent of BookStation and/or its affiliates, as may be applicable.</li>
                <li>This licence does not include: a. any resale or commercial use of this website or its contents; b.
                    any collection and use of any product listings, descriptions, or prices; c. any derivative use of
                    this website or its contents; d. any downloading or copying of account information for the benefit
                    of another seller; e. any use of data mining, robots, or similar data gathering and extraction
                    tools.</li>
                <li>Including but not limited to any copyrighted material, trademarks and/ or other proprietary
                    information, any portion of or this website must not be reproduced, duplicated, imitated, copied,
                    sold, resold, visited, distributed, or otherwise exploited for any commercial purpose without
                    express written consent of BookStation or its affiliates, as may be applicable.</li>
                <li>You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary
                    information (including images, text, page layout, or form) of BookStation and of its affiliates
                    without express written consent.</li>
                <li>You may not use any meta tags or any other hidden text utilising BookStation Private Limited or its
                    affiliates' names and/or trademarks without the express written consent of BookStation and/or its
                    affiliates, as applicable.</li>
                <li>The permission or license granted by BookStation and/or its affiliates, as applicable may be
                    terminated in case of any unauthorised use by you.</li>
                <li>You must not use any BookStation logo or other proprietary graphic or trademark without the express
                    consent of BookStation and/or its affiliates. You may create a hyperlink to the Welcome page of this
                    website, subject to the condition that such link does not represent BookStation and/or its
                    affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive
                    manner.</li>
            </ul>

            <h1 class="user"> USE OF THE WEBSITE</h1>
            <ul class="user1">
                <li>You must not use the website in any way that causes, or is likely to cause, the website or access to
                    it to be interrupted, damaged or impaired in any way.</li>
                <li>You understand that you, and not BookStation, are responsible for all electronic communications and
                    content sent from your computer to us and that you must use the website for lawful purposes only.
                </li>
                <li>You must not use the website for any of the following:</li>s
            </ul>

            <h1 class="user">USER CONTENT ON THE WEBSITE
            </h1>
            <ul class="user1">
                <li>While using the website, you may post reviews, comments and other content, send communications and
                    submit suggestions, ideas, comments, questions, or other information, provided the said content is
                    not illegal, obscene, abusive, threatening, defamatory, invasive of privacy, infringing of
                    intellectual property rights, or otherwise injurious to third parties, or objectionable and does not
                    consist of or contain software viruses, political campaigning, commercial solicitation, chain
                    letters, mass mailings, or any form of spam.</li>
                <li>In case a user uses a false e-mail address, impersonates any person or entity, or otherwise misleads
                    as to the origin of any content, BookStation shall have the right, to remove, refuse, delete or edit
                    any content that in the sole judgement of BookStation violates these Terms and Conditions of Use
                    and/or terminate the permission to access or use this website given to the user.</li>
                <li>With respect to the content or material posted by you, unless specified otherwise by us, you grant
                    BookStation and its affiliates: a. a non-exclusive, royalty-free, irrevocable, perpetual and fully
                    sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works
                    therefrom, distribute, and display such content throughout the world in any media; and b. the right
                    to use the name that you submit in connection with such content.</li>
                <li>You agree that the rights granted by you to us in the content posted by you on the website are
                    irrevocable during the entire period of protection of your intellectual property rights associated
                    with such content and material.</li>
                <li>You agree to perform all further acts necessary to perfect any of the above rights granted by you to
                    BookStation Private Limited, including the execution of deeds and documents, at its request.</li>
                <li>You represent and warrant that you own or otherwise control all of the rights to the content that
                    you post or otherwise provide on or through the website and that, as on the date of provision of the
                    content or material to BookStation: a. the content and material are accurate; b. use of the content
                    and material you supplied does not breach any applicable BookStation Terms and Conditions of Use and
                    will not cause injury to any person or entity (including that the content or material is not
                    defamatory); and c. the content is lawful.</li>
                <li>You agree to indemnify BookStation Private Limited and its affiliates for all claims brought by a
                    third party action, against BookStation and/or its affiliates arising out of or in connection with a
                    breach of any of these warranties by you.</li>
            </ul>

            <h1 class="user">OBJECTIONABLE CONTENT</h1>
            <ul class="user1">
                <li>BookStation lists a number of products for sale offered by sellers on the website and hosts a vast
                    number of comments, rendering it incapable of being aware at all times of the contents of each
                    product listed for sale, or each comment or review that is displayed.</li>
                <li>If you believe that any content on the website is "Objectionable Content", i.e. :</li>
            </ul>

            <h1 class="user">INTELLECTUAL PROPERTY CLAIMS</h1>
            <ul class="user1">
                <li>BookStation Private Limited and its affiliates do not infringe upon the intellectual property rights
                    of others and respect the Intellectual Property of others.</li>
                <li>If you believe that your intellectual property rights have been used in a way that makes up for any
                    concerns of infringement, kindly notify us immediately by following our procedure for Notice for
                    Claim of Infringement of Rights.</li>
            </ul>

        </div>

    </div>




    <!----------- footer ----------------->

    <?php include('footer.php'); ?>
    
</body>

</html>